/**
 * Seed listing repository.
 *
 * The explorer runs without a remote backend, so this module is the data
 * source of record. It ships 67 hand-authored listings spanning 15 regions,
 * each expanded from a compact definition into a complete `PropertyListing`
 * (slug, derived review breakdown, calendar blocks, timestamps, host profile).
 *
 * Photography notes:
 * - Every Unsplash photo id in `IMAGE_POOL` and every host avatar id in
 *   `SEED_HOSTS` was verified to return HTTP 200 from `images.unsplash.com`.
 * - Galleries are assigned deterministically per listing so a gallery never
 *   repeats a photo internally and neighbouring cards do not share visuals.
 * - Two blueprint listings from the project plan keep their explicit galleries.
 *
 * Determinism: `generateSeedListings(referenceDate)` derives calendar blocks and
 * timestamps from the supplied date, so availability always sits in the future
 * relative to the viewer while remaining fully reproducible for a given day.
 */

import {
  isIsoDateString,
  isValidListing,
  VALIDATION_LIMITS,
  type Amenity,
  type AvailabilityRange,
  type Coordinates,
  type HostProfile,
  type ListingCapacity,
  type PropertyListing,
  type PropertyType,
  type ReviewBreakdown,
} from "../types";
import { APP_CONFIG } from "./config";
import {
  addDays,
  clamp,
  roundTo,
  slugify,
  stableHash,
  toIsoDateTimeString,
  toIsoDateString,
} from "./utils";

/* -------------------------------------------------------------------------- */
/* 1. Media helpers                                                           */
/* -------------------------------------------------------------------------- */

const UNSPLASH_ORIGIN = "https://images.unsplash.com";

/** Curated, network-verified property photography pool. */
const IMAGE_POOL: readonly string[] = [
  "photo-1600596542815-ffad4c1539a9",
  "photo-1600585154340-be6161a56a0c",
  "photo-1600607687939-ce8a6c25118c",
  "photo-1512917774080-9991f1c4c750",
  "photo-1560448204-e02f11c3d0e2",
  "photo-1536376072261-38c75010e6c9",
  "photo-1505691938895-1758d7feb511",
  "photo-1568605114967-8130f3a36994",
  "photo-1570129477492-45c003edd2be",
  "photo-1583608205776-bfd35f0d9f83",
  "photo-1613490493576-7fde63acd811",
  "photo-1600566753190-17f0baa2a6c3",
  "photo-1600210492486-724fe5c67fb0",
  "photo-1600607687920-4e2a09cf159d",
  "photo-1600047509807-ba8f99d2cdde",
  "photo-1600566753086-00f18fb6b3ea",
  "photo-1600566752355-35792bedcfea",
  "photo-1600585154526-990dced4db0d",
  "photo-1600121848594-d8644e57abab",
  "photo-1600573472550-8090b5e0745e",
  "photo-1600585152220-90363fe7e115",
  "photo-1580587771525-78b9dba3b914",
  "photo-1564013799919-ab600027ffc6",
  "photo-1518780664697-55e3ad937233",
  "photo-1523217582562-09d0def993a6",
  "photo-1449844908441-8829872d2607",
  "photo-1502672260266-1c1ef2d93688",
  "photo-1493809842364-78817add7ffb",
  "photo-1484154218962-a197022b5858",
  "photo-1554995207-c18c203602cb",
  "photo-1556228453-efd6c1ff04f6",
  "photo-1567767292278-a4f21aa2d36e",
  "photo-1598928506311-c55ded91a20c",
  "photo-1600607688969-a5bfcd646154",
  "photo-1600607688960-e095ff83135c",
  "photo-1600607688066-890987f18a86",
  "photo-1600585154084-4e5fe7c39198",
  "photo-1600585154363-67eb9e2e2099",
  "photo-1600047509358-9dc75507daeb",
  "photo-1600047509782-20d39509f26d",
  "photo-1613977257363-707ba9348227",
  "photo-1613977257592-4871e5fcd7c4",
  "photo-1512918728675-ed5a9ecdebfd",
  "photo-1522708323590-d24dbb6b0267",
  "photo-1502005229762-cf1b2da7c5d6",
  "photo-1493663284031-b7e3aefcae8e",
  "photo-1586023492125-27b2c045efd7",
  "photo-1583847268964-b28dc8f51f92",
  "photo-1571055107559-3e67626fa8be",
  "photo-1416331108676-a22ccb276e35",
  "photo-1470770841072-f978cf4d019e",
  "photo-1476514525535-07fb3b4ae5f1",
  "photo-1504280390367-361c6d9f38f4",
  "photo-1449158743715-0a90ebb6d2d8",
  "photo-1510798831971-661eb04b3739",
  "photo-1615529182904-14819c35db37",
  "photo-1592595896551-12b371d546d5",
  "photo-1560185007-cde436f6a4d0",
  "photo-1560185008-b033106af5c3",
  "photo-1560185127-6ed189bf02f4",
  "photo-1560184897-ae75f418493e",
];

type GalleryTuple = readonly [string, string, string, ...string[]];

function propertyImage(photoId: string, width = 1600): string {
  return `${UNSPLASH_ORIGIN}/${photoId}?auto=format&fit=crop&w=${width}&q=80`;
}

function avatarImage(photoId: string, size = 200): string {
  return `${UNSPLASH_ORIGIN}/${photoId}?auto=format&fit=crop&w=${size}&h=${size}&q=80`;
}

/**
 * Deterministic gallery rotation. Offsets are pairwise distinct modulo the pool
 * length, so a single gallery can never show the same photo twice.
 */
function selectGallery(
  seedIndex: number,
  pricePerNight: number,
): GalleryTuple {
  const base = (seedIndex * 7 + 5) % IMAGE_POOL.length;
  const offsets = pricePerNight >= 600 ? [0, 11, 23, 37, 49] : [0, 11, 23, 37];
  const picked = offsets.map(
    (offset) => IMAGE_POOL[(base + offset) % IMAGE_POOL.length],
  );
  const [first, second, third, ...rest] = picked;
  return [first, second, third, ...rest];
}

/* -------------------------------------------------------------------------- */
/* 2. Host roster                                                             */
/* -------------------------------------------------------------------------- */

export interface SeedHostDefinition {
  readonly id: string;
  readonly name: string;
  readonly avatarPhotoId: string;
  readonly isSuperhost: boolean;
  readonly joinedDate: string;
  readonly responseRatePercent: number;
  readonly responseTimeMinutes: number;
}

export const SEED_HOSTS: readonly SeedHostDefinition[] = [
  {
    id: "host-101",
    name: "Elena Rostova",
    avatarPhotoId: "photo-1534528741775-53994a69daeb",
    isSuperhost: true,
    joinedDate: "March 2018",
    responseRatePercent: 100,
    responseTimeMinutes: 15,
  },
  {
    id: "host-102",
    name: "Marcus Chen",
    avatarPhotoId: "photo-1507003211169-0a1dd7228f2d",
    isSuperhost: true,
    joinedDate: "September 2019",
    responseRatePercent: 98,
    responseTimeMinutes: 30,
  },
  {
    id: "host-103",
    name: "Priya Raghunathan",
    avatarPhotoId: "photo-1494790108377-be9c29b29330",
    isSuperhost: false,
    joinedDate: "June 2021",
    responseRatePercent: 94,
    responseTimeMinutes: 55,
  },
  {
    id: "host-104",
    name: "Daniel Okafor",
    avatarPhotoId: "photo-1500648767791-00dcc994a43e",
    isSuperhost: true,
    joinedDate: "January 2017",
    responseRatePercent: 99,
    responseTimeMinutes: 20,
  },
  {
    id: "host-105",
    name: "Sofia Marchetti",
    avatarPhotoId: "photo-1544005313-94ddf0286df2",
    isSuperhost: false,
    joinedDate: "April 2022",
    responseRatePercent: 92,
    responseTimeMinutes: 70,
  },
  {
    id: "host-106",
    name: "Jake Whitfield",
    avatarPhotoId: "photo-1506794778202-cad84cf45f1d",
    isSuperhost: false,
    joinedDate: "August 2020",
    responseRatePercent: 90,
    responseTimeMinutes: 85,
  },
  {
    id: "host-107",
    name: "Camille Dubois",
    avatarPhotoId: "photo-1517841905240-472988babdf9",
    isSuperhost: true,
    joinedDate: "May 2016",
    responseRatePercent: 100,
    responseTimeMinutes: 10,
  },
  {
    id: "host-108",
    name: "Harrison Blake",
    avatarPhotoId: "photo-1519085360753-af0119f7cbe7",
    isSuperhost: false,
    joinedDate: "October 2021",
    responseRatePercent: 95,
    responseTimeMinutes: 45,
  },
  {
    id: "host-109",
    name: "Naomi Feldman",
    avatarPhotoId: "photo-1508214751196-bcfd4ca60f91",
    isSuperhost: true,
    joinedDate: "February 2018",
    responseRatePercent: 99,
    responseTimeMinutes: 25,
  },
  {
    id: "host-110",
    name: "Andre Silva",
    avatarPhotoId: "photo-1524504388940-b1c1722653e1",
    isSuperhost: false,
    joinedDate: "July 2021",
    responseRatePercent: 93,
    responseTimeMinutes: 60,
  },
  {
    id: "host-111",
    name: "Greta Lindqvist",
    avatarPhotoId: "photo-1531427186611-ecfd6d936c79",
    isSuperhost: true,
    joinedDate: "November 2016",
    responseRatePercent: 100,
    responseTimeMinutes: 12,
  },
  {
    id: "host-112",
    name: "Tobias Lang",
    avatarPhotoId: "photo-1472099645785-5658abf4ff4e",
    isSuperhost: false,
    joinedDate: "December 2020",
    responseRatePercent: 91,
    responseTimeMinutes: 75,
  },
  {
    id: "host-113",
    name: "Marisol Ortega",
    avatarPhotoId: "photo-1487412720507-e7ab37603c6f",
    isSuperhost: true,
    joinedDate: "March 2017",
    responseRatePercent: 99,
    responseTimeMinutes: 18,
  },
  {
    id: "host-114",
    name: "Kenji Nakamura",
    avatarPhotoId: "photo-1573496359142-b8d87734a5a2",
    isSuperhost: false,
    joinedDate: "May 2022",
    responseRatePercent: 89,
    responseTimeMinutes: 95,
  },
  {
    id: "host-115",
    name: "Brielle Fontaine",
    avatarPhotoId: "photo-1580489944761-15a19d654956",
    isSuperhost: false,
    joinedDate: "September 2020",
    responseRatePercent: 96,
    responseTimeMinutes: 40,
  },
  {
    id: "host-116",
    name: "Wade Holloway",
    avatarPhotoId: "photo-1607746882042-944635dfe10e",
    isSuperhost: true,
    joinedDate: "April 2015",
    responseRatePercent: 100,
    responseTimeMinutes: 8,
  },
  {
    id: "host-117",
    name: "Anika Petrova",
    avatarPhotoId: "photo-1614289371518-722f2615943d",
    isSuperhost: false,
    joinedDate: "January 2022",
    responseRatePercent: 92,
    responseTimeMinutes: 65,
  },
  {
    id: "host-118",
    name: "Desmond Clarke",
    avatarPhotoId: "photo-1438761681033-6461ffad8d80",
    isSuperhost: false,
    joinedDate: "June 2019",
    responseRatePercent: 97,
    responseTimeMinutes: 35,
  },
  {
    id: "host-119",
    name: "Yuki Tanaka",
    avatarPhotoId: "photo-1560250097-0b93528c311a",
    isSuperhost: false,
    joinedDate: "March 2023",
    responseRatePercent: 88,
    responseTimeMinutes: 110,
  },
  {
    id: "host-120",
    name: "Rosa Jimenez",
    avatarPhotoId: "photo-1499996860823-5214fcc65f8f",
    isSuperhost: true,
    joinedDate: "August 2017",
    responseRatePercent: 99,
    responseTimeMinutes: 22,
  },
  {
    id: "host-121",
    name: "Elliot Grant",
    avatarPhotoId: "photo-1557862921-37829c790f19",
    isSuperhost: false,
    joinedDate: "February 2021",
    responseRatePercent: 94,
    responseTimeMinutes: 50,
  },
  {
    id: "host-122",
    name: "Hannah Bergstrom",
    avatarPhotoId: "photo-1542206395-9feb3edaa68d",
    isSuperhost: false,
    joinedDate: "November 2021",
    responseRatePercent: 93,
    responseTimeMinutes: 58,
  },
  {
    id: "host-123",
    name: "Omar Haddad",
    avatarPhotoId: "photo-1519345182560-3f2917c472ef",
    isSuperhost: true,
    joinedDate: "October 2015",
    responseRatePercent: 100,
    responseTimeMinutes: 14,
  },
  {
    id: "host-124",
    name: "Lydia Ashworth",
    avatarPhotoId: "photo-1566492031773-4f4e44671857",
    isSuperhost: false,
    joinedDate: "July 2022",
    responseRatePercent: 90,
    responseTimeMinutes: 80,
  },
];

const HOSTS_BY_ID: ReadonlyMap<string, SeedHostDefinition> = new Map(
  SEED_HOSTS.map((host) => [host.id, host]),
);

/* -------------------------------------------------------------------------- */
/* 3. Listing definitions                                                     */
/* -------------------------------------------------------------------------- */

export interface SeedListingDefinition {
  readonly id: string;
  readonly title: string;
  readonly description: string;
  readonly propertyType: PropertyType;
  readonly pricePerNight: number;
  readonly cleaningFee: number;
  readonly ratingAverage: number;
  readonly ratingCount: number;
  readonly minNights: number;
  readonly isInstantBook: boolean;
  readonly isRareFind: boolean;
  readonly hostId: string;
  readonly coordinates: Coordinates;
  readonly street: string;
  readonly city: string;
  readonly state: string;
  readonly zipCode: string;
  readonly neighborhood: string;
  readonly country?: string;
  readonly capacity: ListingCapacity;
  readonly amenities: readonly Amenity[];
  /** Calendar blocks as `[startOffsetDays, endOffsetDays]` from the reference date. */
  readonly blocked: readonly (readonly [number, number])[];
  readonly listedDaysAgo: number;
  readonly updatedDaysAgo: number;
  /** Optional explicit gallery; otherwise a deterministic pool rotation is used. */
  readonly images?: GalleryTuple;
}

const SEED_LISTING_DEFINITIONS: readonly SeedListingDefinition[] = [
  /* ------------------------------- Los Angeles ---------------------------- */
  {
    id: "prop-001",
    title: "Architectural Hilltop Sanctuary with Panoramic Ocean Views",
    description:
      "Designed by renowned modernist architects, this glass pavilion sits atop the Pacific Palisades offering 270-degree ocean and mountain horizons.",
    propertyType: "villa",
    pricePerNight: 850,
    cleaningFee: 220,
    ratingAverage: 4.98,
    ratingCount: 142,
    minNights: 2,
    isInstantBook: true,
    isRareFind: true,
    hostId: "host-101",
    images: [
      "photo-1600596542815-ffad4c1539a9",
      "photo-1600585154340-be6161a56a0c",
      "photo-1600607687939-ce8a6c25118c",
      "photo-1512917774080-9991f1c4c750",
    ],
    coordinates: { lat: 34.0489, lng: -118.5283 },
    street: "14920 Corona Del Mar",
    city: "Pacific Palisades",
    state: "CA",
    zipCode: "90272",
    neighborhood: "Pacific Palisades",
    capacity: { maxGuests: 8, bedrooms: 4, beds: 5, bathrooms: 4.5 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "dryer",
      "air_conditioning",
      "pool",
      "hot_tub",
      "free_parking",
      "ev_charger",
      "workspace",
      "bbq_grill",
      "smoke_alarm",
    ],
    blocked: [
      [6, 13],
      [34, 41],
    ],
    listedDaysAgo: 584,
    updatedDaysAgo: 21,
  },
  {
    id: "prop-002",
    title: "Minimalist Downtown Loft in Historic District",
    description:
      "Double-height concrete ceilings, exposed original brickwork, and curated mid-century furnishings in the heart of the Arts District.",
    propertyType: "loft",
    pricePerNight: 245,
    cleaningFee: 95,
    ratingAverage: 4.92,
    ratingCount: 88,
    minNights: 1,
    isInstantBook: false,
    isRareFind: false,
    hostId: "host-102",
    images: [
      "photo-1560448204-e02f11c3d0e2",
      "photo-1536376072261-38c75010e6c9",
      "photo-1505691938895-1758d7feb511",
    ],
    coordinates: { lat: 34.0407, lng: -118.2337 },
    street: "580 Mateo St Unit 402",
    city: "Los Angeles",
    state: "CA",
    zipCode: "90013",
    neighborhood: "Arts District",
    capacity: { maxGuests: 2, bedrooms: 1, beds: 1, bathrooms: 1 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "air_conditioning",
      "workspace",
      "gym",
      "pets_allowed",
      "smoke_alarm",
    ],
    blocked: [
      [2, 9],
      [18, 24],
      [45, 52],
    ],
    listedDaysAgo: 512,
    updatedDaysAgo: 33,
  },
  {
    id: "prop-003",
    title: "Sun-Drenched Venice Bungalow Steps from the Boardwalk",
    description:
      "A restored 1920s bungalow with a succulent-filled courtyard, outdoor shower, and bikes waiting in the garage for the two-block ride to the sand.",
    propertyType: "house",
    pricePerNight: 189,
    cleaningFee: 85,
    ratingAverage: 4.87,
    ratingCount: 214,
    minNights: 2,
    isInstantBook: true,
    isRareFind: false,
    hostId: "host-103",
    coordinates: { lat: 33.9905, lng: -118.4663 },
    street: "742 Nowita Pl",
    city: "Venice",
    state: "CA",
    zipCode: "90291",
    neighborhood: "Venice",
    capacity: { maxGuests: 4, bedrooms: 2, beds: 2, bathrooms: 1 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "dryer",
      "heating",
      "patio",
      "free_parking",
      "workspace",
      "pets_allowed",
      "smoke_alarm",
    ],
    blocked: [
      [4, 8],
      [27, 31],
    ],
    listedDaysAgo: 431,
    updatedDaysAgo: 12,
  },
  {
    id: "prop-004",
    title: "Silver Lake Hillside Retreat with Reservoir Views",
    description:
      "Cantilevered over the reservoir path, this three-storey home pairs a chef's kitchen with a cedar deck built for long golden-hour dinners.",
    propertyType: "house",
    pricePerNight: 320,
    cleaningFee: 130,
    ratingAverage: 4.94,
    ratingCount: 96,
    minNights: 2,
    isInstantBook: true,
    isRareFind: true,
    hostId: "host-104",
    coordinates: { lat: 34.0869, lng: -118.2702 },
    street: "2210 Lake Shore Ave",
    city: "Los Angeles",
    state: "CA",
    zipCode: "90039",
    neighborhood: "Silver Lake",
    capacity: { maxGuests: 6, bedrooms: 3, beds: 4, bathrooms: 2 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "dryer",
      "air_conditioning",
      "heating",
      "free_parking",
      "patio",
      "bbq_grill",
      "workspace",
      "smoke_alarm",
    ],
    blocked: [
      [9, 16],
      [38, 44],
    ],
    listedDaysAgo: 366,
    updatedDaysAgo: 8,
  },
  {
    id: "prop-005",
    title: "Skyline Corner Apartment Above Grand Central Market",
    description:
      "Floor-to-ceiling glass on the twentieth floor of a Hill Street tower, with the market, Angels Flight, and the Broad all inside a ten-minute walk.",
    propertyType: "apartment",
    pricePerNight: 168,
    cleaningFee: 70,
    ratingAverage: 4.79,
    ratingCount: 163,
    minNights: 1,
    isInstantBook: true,
    isRareFind: false,
    hostId: "host-105",
    coordinates: { lat: 34.0508, lng: -118.2492 },
    street: "308 S Hill St Apt 2104",
    city: "Los Angeles",
    state: "CA",
    zipCode: "90013",
    neighborhood: "Downtown",
    capacity: { maxGuests: 3, bedrooms: 1, beds: 2, bathrooms: 1 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "dryer",
      "air_conditioning",
      "gym",
      "pool",
      "workspace",
      "smoke_alarm",
    ],
    blocked: [
      [1, 6],
      [21, 28],
    ],
    listedDaysAgo: 289,
    updatedDaysAgo: 5,
  },
  {
    id: "prop-006",
    title: "Bright Studio Near Universal with Private Patio",
    description:
      "A calm, plant-filled studio with a fenced patio, blackout shades, and a dedicated desk for remote work five minutes from the studio tour.",
    propertyType: "studio",
    pricePerNight: 112,
    cleaningFee: 55,
    ratingAverage: 4.72,
    ratingCount: 137,
    minNights: 1,
    isInstantBook: true,
    isRareFind: false,
    hostId: "host-106",
    coordinates: { lat: 34.1395, lng: -118.387 },
    street: "4218 Ventura Blvd Unit 6",
    city: "Studio City",
    state: "CA",
    zipCode: "91604",
    neighborhood: "Studio City",
    capacity: { maxGuests: 2, bedrooms: 0, beds: 1, bathrooms: 1 },
    amenities: [
      "wifi",
      "kitchen",
      "air_conditioning",
      "heating",
      "free_parking",
      "patio",
      "workspace",
      "smoke_alarm",
    ],
    blocked: [
      [3, 7],
      [25, 30],
    ],
    listedDaysAgo: 254,
    updatedDaysAgo: 17,
  },

  /* ---------------------------- Malibu & Topanga -------------------------- */
  {
    id: "prop-007",
    title: "Malibu Colony Beach House with Private Sand Deck",
    description:
      "Direct sand access from a wraparound deck, an outdoor rain shower, and a fire table positioned exactly where the sun drops into the water.",
    propertyType: "house",
    pricePerNight: 1250,
    cleaningFee: 320,
    ratingAverage: 4.99,
    ratingCount: 78,
    minNights: 3,
    isInstantBook: false,
    isRareFind: true,
    hostId: "host-107",
    coordinates: { lat: 34.0323, lng: -118.689 },
    street: "23456 Malibu Colony Rd",
    city: "Malibu",
    state: "CA",
    zipCode: "90265",
    neighborhood: "Malibu Colony",
    capacity: { maxGuests: 8, bedrooms: 4, beds: 5, bathrooms: 3.5 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "dryer",
      "heating",
      "air_conditioning",
      "hot_tub",
      "bbq_grill",
      "patio",
      "free_parking",
      "ev_charger",
      "workspace",
      "smoke_alarm",
    ],
    blocked: [
      [10, 20],
      [40, 50],
    ],
    listedDaysAgo: 623,
    updatedDaysAgo: 26,
  },
  {
    id: "prop-008",
    title: "Point Dume Modern Villa Overlooking the Pacific",
    description:
      "A glass-walled villa with an infinity pool, cantilevered terrace, and a private path to the bluff above Westward Beach.",
    propertyType: "villa",
    pricePerNight: 985,
    cleaningFee: 260,
    ratingAverage: 4.96,
    ratingCount: 112,
    minNights: 2,
    isInstantBook: true,
    isRareFind: true,
    hostId: "host-108",
    coordinates: { lat: 34.0017, lng: -118.8066 },
    street: "28853 Cliffside Dr",
    city: "Malibu",
    state: "CA",
    zipCode: "90265",
    neighborhood: "Point Dume",
    capacity: { maxGuests: 6, bedrooms: 3, beds: 4, bathrooms: 3 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "dryer",
      "pool",
      "hot_tub",
      "free_parking",
      "ev_charger",
      "bbq_grill",
      "patio",
      "workspace",
      "smoke_alarm",
    ],
    blocked: [
      [5, 12],
      [30, 37],
    ],
    listedDaysAgo: 498,
    updatedDaysAgo: 14,
  },
  {
    id: "prop-009",
    title: "Redwood Canyon Cabin in Topanga State Park",
    description:
      "A quiet timber cabin on a seasonal creek, with a wood-burning stove, screened porch, and trailheads leaving directly from the driveway.",
    propertyType: "cabin",
    pricePerNight: 268,
    cleaningFee: 110,
    ratingAverage: 4.9,
    ratingCount: 64,
    minNights: 2,
    isInstantBook: false,
    isRareFind: false,
    hostId: "host-109",
    coordinates: { lat: 34.0936, lng: -118.601 },
    street: "1045 Old Topanga Canyon Rd",
    city: "Topanga",
    state: "CA",
    zipCode: "90290",
    neighborhood: "Topanga",
    capacity: { maxGuests: 4, bedrooms: 2, beds: 2, bathrooms: 1 },
    amenities: [
      "wifi",
      "kitchen",
      "heating",
      "free_parking",
      "bbq_grill",
      "patio",
      "workspace",
      "pets_allowed",
      "smoke_alarm",
    ],
    blocked: [
      [7, 14],
      [29, 35],
    ],
    listedDaysAgo: 341,
    updatedDaysAgo: 19,
  },
  {
    id: "prop-010",
    title: "Sunlit Ocean Park Studio, Two Blocks to the Sand",
    description:
      "A crisp coastal studio with a Murphy bed, galley kitchen, and beach chairs stacked by the door for the short walk to Ocean Park beach.",
    propertyType: "studio",
    pricePerNight: 158,
    cleaningFee: 60,
    ratingAverage: 4.81,
    ratingCount: 201,
    minNights: 1,
    isInstantBook: true,
    isRareFind: false,
    hostId: "host-110",
    coordinates: { lat: 34.0078, lng: -118.4812 },
    street: "526 Ocean Park Blvd Unit 3",
    city: "Santa Monica",
    state: "CA",
    zipCode: "90405",
    neighborhood: "Ocean Park",
    capacity: { maxGuests: 2, bedrooms: 0, beds: 1, bathrooms: 1 },
    amenities: [
      "wifi",
      "kitchen",
      "heating",
      "washer",
      "workspace",
      "patio",
      "smoke_alarm",
    ],
    blocked: [
      [2, 5],
      [23, 29],
    ],
    listedDaysAgo: 212,
    updatedDaysAgo: 6,
  },

  /* ------------------------------- Lake Tahoe ----------------------------- */
  {
    id: "prop-011",
    title: "Lakefront Log Cabin with Private Pier and Fireplace",
    description:
      "A hand-built log home with seventy feet of private shoreline, a kayak launch, and a stone hearth that anchors the great room.",
    propertyType: "cabin",
    pricePerNight: 465,
    cleaningFee: 180,
    ratingAverage: 4.95,
    ratingCount: 187,
    minNights: 3,
    isInstantBook: true,
    isRareFind: true,
    hostId: "host-111",
    coordinates: { lat: 39.093, lng: -120.043 },
    street: "7210 West Lake Blvd",
    city: "Tahoma",
    state: "CA",
    zipCode: "96142",
    neighborhood: "Tahoma",
    capacity: { maxGuests: 6, bedrooms: 3, beds: 4, bathrooms: 2 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "dryer",
      "heating",
      "lake_access",
      "free_parking",
      "bbq_grill",
      "patio",
      "workspace",
      "smoke_alarm",
    ],
    blocked: [
      [8, 15],
      [33, 40],
    ],
    listedDaysAgo: 552,
    updatedDaysAgo: 11,
  },
  {
    id: "prop-012",
    title: "Ski-In/Ski-Out Chalet at Palisades Tahoe",
    description:
      "Boots on at the door, skis on at the run: a timber chalet with a loft bunk room and a hot tub facing the KT-22 ridgeline.",
    propertyType: "cabin",
    pricePerNight: 540,
    cleaningFee: 210,
    ratingAverage: 4.93,
    ratingCount: 154,
    minNights: 3,
    isInstantBook: true,
    isRareFind: true,
    hostId: "host-112",
    coordinates: { lat: 39.1969, lng: -120.2345 },
    street: "1750 Squaw Valley Rd Unit 12",
    city: "Olympic Valley",
    state: "CA",
    zipCode: "96146",
    neighborhood: "Olympic Valley",
    capacity: { maxGuests: 8, bedrooms: 3, beds: 5, bathrooms: 2.5 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "dryer",
      "heating",
      "hot_tub",
      "ski_in_out",
      "free_parking",
      "ev_charger",
      "workspace",
      "smoke_alarm",
    ],
    blocked: [
      [4, 11],
      [26, 34],
    ],
    listedDaysAgo: 476,
    updatedDaysAgo: 9,
  },
  {
    id: "prop-013",
    title: "South Lake Townhouse a Short Walk to Heavenly Gondola",
    description:
      "A three-level townhouse with a garage for gear, a gas fireplace, and the Heavenly gondola plaza eight minutes away on foot.",
    propertyType: "townhouse",
    pricePerNight: 289,
    cleaningFee: 125,
    ratingAverage: 4.86,
    ratingCount: 231,
    minNights: 2,
    isInstantBook: true,
    isRareFind: false,
    hostId: "host-113",
    coordinates: { lat: 38.9551, lng: -119.942 },
    street: "4130 Cedar Ave Unit 7",
    city: "South Lake Tahoe",
    state: "CA",
    zipCode: "96150",
    neighborhood: "Bijou",
    capacity: { maxGuests: 6, bedrooms: 2, beds: 3, bathrooms: 2 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "dryer",
      "heating",
      "free_parking",
      "patio",
      "workspace",
      "pets_allowed",
      "smoke_alarm",
    ],
    blocked: [
      [6, 12],
      [31, 38],
    ],
    listedDaysAgo: 398,
    updatedDaysAgo: 15,
  },
  {
    id: "prop-014",
    title: "Truckee Loft Above the Historic Downtown Shops",
    description:
      "An industrial loft with reclaimed fir beams, a compact chef's kitchen, and the Truckee River trail one block from the front door.",
    propertyType: "loft",
    pricePerNight: 198,
    cleaningFee: 80,
    ratingAverage: 4.78,
    ratingCount: 88,
    minNights: 1,
    isInstantBook: true,
    isRareFind: false,
    hostId: "host-114",
    coordinates: { lat: 39.3279, lng: -120.1833 },
    street: "10094 Donner Pass Rd Apt 2",
    city: "Truckee",
    state: "CA",
    zipCode: "96161",
    neighborhood: "Downtown Truckee",
    capacity: { maxGuests: 4, bedrooms: 1, beds: 2, bathrooms: 1 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "heating",
      "workspace",
      "free_parking",
      "smoke_alarm",
    ],
    blocked: [
      [3, 9],
      [22, 27],
    ],
    listedDaysAgo: 267,
    updatedDaysAgo: 7,
  },
  {
    id: "prop-015",
    title: "Emerald Bay A-Frame with Forest Deck and Sauna",
    description:
      "A cedar A-frame tucked into the pines above Emerald Bay, with a barrel sauna, fire pit, and a deck built around two mature firs.",
    propertyType: "cabin",
    pricePerNight: 355,
    cleaningFee: 140,
    ratingAverage: 4.97,
    ratingCount: 119,
    minNights: 2,
    isInstantBook: false,
    isRareFind: true,
    hostId: "host-115",
    coordinates: { lat: 38.9546, lng: -120.0969 },
    street: "890 Emerald Bay Rd",
    city: "South Lake Tahoe",
    state: "CA",
    zipCode: "96150",
    neighborhood: "Emerald Bay",
    capacity: { maxGuests: 5, bedrooms: 2, beds: 3, bathrooms: 1.5 },
    amenities: [
      "wifi",
      "kitchen",
      "heating",
      "hot_tub",
      "lake_access",
      "free_parking",
      "bbq_grill",
      "patio",
      "workspace",
      "smoke_alarm",
    ],
    blocked: [
      [5, 13],
      [36, 43],
    ],
    listedDaysAgo: 444,
    updatedDaysAgo: 10,
  },

  /* ------------------------------ Big Bear Lake --------------------------- */
  {
    id: "prop-016",
    title: "Big Bear Lakefront Cabin with Boat Dock",
    description:
      "A north-shore cabin with a private dock, paddleboards included, and lake views framed by every window in the living room.",
    propertyType: "cabin",
    pricePerNight: 325,
    cleaningFee: 135,
    ratingAverage: 4.89,
    ratingCount: 176,
    minNights: 2,
    isInstantBook: true,
    isRareFind: false,
    hostId: "host-115",
    coordinates: { lat: 34.2439, lng: -116.9114 },
    street: "39145 North Shore Dr",
    city: "Fawnskin",
    state: "CA",
    zipCode: "92333",
    neighborhood: "Fawnskin",
    capacity: { maxGuests: 7, bedrooms: 3, beds: 4, bathrooms: 2 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "dryer",
      "heating",
      "lake_access",
      "free_parking",
      "bbq_grill",
      "patio",
      "smoke_alarm",
    ],
    blocked: [
      [7, 14],
      [28, 36],
    ],
    listedDaysAgo: 359,
    updatedDaysAgo: 13,
  },
  {
    id: "prop-017",
    title: "Timber A-Frame with Hot Tub Near Snow Summit",
    description:
      "Classic mountain A-frame with a lofted sleeping nook, pellet stove, and a hot tub on the deck under the pines.",
    propertyType: "cabin",
    pricePerNight: 249,
    cleaningFee: 105,
    ratingAverage: 4.84,
    ratingCount: 203,
    minNights: 2,
    isInstantBook: true,
    isRareFind: false,
    hostId: "host-116",
    coordinates: { lat: 34.2317, lng: -116.891 },
    street: "812 Pine Knot Ave",
    city: "Big Bear Lake",
    state: "CA",
    zipCode: "92315",
    neighborhood: "Big Bear Village",
    capacity: { maxGuests: 6, bedrooms: 2, beds: 3, bathrooms: 2 },
    amenities: [
      "wifi",
      "kitchen",
      "heating",
      "hot_tub",
      "free_parking",
      "bbq_grill",
      "patio",
      "workspace",
      "pets_allowed",
      "smoke_alarm",
    ],
    blocked: [
      [4, 10],
      [25, 32],
    ],
    listedDaysAgo: 312,
    updatedDaysAgo: 16,
  },
  {
    id: "prop-018",
    title: "Modern Mountain Townhouse with Lake Views",
    description:
      "A remodeled end-unit townhouse with an EV charger in the garage, a balcony facing the lake, and a sledding hill next door.",
    propertyType: "townhouse",
    pricePerNight: 279,
    cleaningFee: 115,
    ratingAverage: 4.91,
    ratingCount: 94,
    minNights: 2,
    isInstantBook: true,
    isRareFind: false,
    hostId: "host-117",
    coordinates: { lat: 34.256, lng: -116.948 },
    street: "1200 Summit Blvd Unit 4",
    city: "Big Bear Lake",
    state: "CA",
    zipCode: "92315",
    neighborhood: "Summit Estates",
    capacity: { maxGuests: 6, bedrooms: 3, beds: 3, bathrooms: 2.5 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "dryer",
      "heating",
      "air_conditioning",
      "free_parking",
      "ev_charger",
      "patio",
      "workspace",
      "smoke_alarm",
    ],
    blocked: [
      [6, 11],
      [30, 35],
    ],
    listedDaysAgo: 276,
    updatedDaysAgo: 4,
  },
  {
    id: "prop-019",
    title: "Cozy Village Studio Steps to the Marina",
    description:
      "A compact studio with a queen bed, kitchenette, and a shared deck overlooking the marina — walkable to every Village restaurant.",
    propertyType: "studio",
    pricePerNight: 132,
    cleaningFee: 60,
    ratingAverage: 4.7,
    ratingCount: 148,
    minNights: 1,
    isInstantBook: true,
    isRareFind: false,
    hostId: "host-118",
    coordinates: { lat: 34.2436, lng: -116.911 },
    street: "40708 Big Bear Blvd Unit 9",
    city: "Big Bear Lake",
    state: "CA",
    zipCode: "92315",
    neighborhood: "Big Bear Village",
    capacity: { maxGuests: 2, bedrooms: 0, beds: 1, bathrooms: 1 },
    amenities: [
      "wifi",
      "kitchen",
      "heating",
      "free_parking",
      "workspace",
      "smoke_alarm",
    ],
    blocked: [
      [2, 6],
      [20, 26],
    ],
    listedDaysAgo: 198,
    updatedDaysAgo: 20,
  },

  /* ------------------------- Joshua Tree & Palm Springs ------------------- */
  {
    id: "prop-020",
    title: "Joshua Tree Desert Dome with Stargazing Deck",
    description:
      "A geodesic dome on five fenced acres with a sunken fire pit, hammock grove, and zero light pollution after dark.",
    propertyType: "house",
    pricePerNight: 285,
    cleaningFee: 120,
    ratingAverage: 4.96,
    ratingCount: 268,
    minNights: 2,
    isInstantBook: true,
    isRareFind: true,
    hostId: "host-113",
    coordinates: { lat: 34.1347, lng: -116.3131 },
    street: "6125 Sunfair Rd",
    city: "Joshua Tree",
    state: "CA",
    zipCode: "92252",
    neighborhood: "Sunfair",
    capacity: { maxGuests: 4, bedrooms: 2, beds: 2, bathrooms: 1 },
    amenities: [
      "wifi",
      "kitchen",
      "air_conditioning",
      "heating",
      "hot_tub",
      "free_parking",
      "bbq_grill",
      "patio",
      "workspace",
      "smoke_alarm",
    ],
    blocked: [
      [5, 12],
      [27, 33],
    ],
    listedDaysAgo: 468,
    updatedDaysAgo: 18,
  },
  {
    id: "prop-021",
    title: "Palm Springs Mid-Century Pool Villa",
    description:
      "A restored 1958 Alexander villa with a saltwater pool, mountain-facing patio, and original terrazzo floors throughout.",
    propertyType: "villa",
    pricePerNight: 620,
    cleaningFee: 240,
    ratingAverage: 4.94,
    ratingCount: 141,
    minNights: 3,
    isInstantBook: true,
    isRareFind: true,
    hostId: "host-108",
    coordinates: { lat: 33.8303, lng: -116.5453 },
    street: "1148 E Palm Canyon Dr",
    city: "Palm Springs",
    state: "CA",
    zipCode: "92264",
    neighborhood: "Deepwell",
    capacity: { maxGuests: 8, bedrooms: 4, beds: 4, bathrooms: 3 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "dryer",
      "air_conditioning",
      "pool",
      "hot_tub",
      "free_parking",
      "ev_charger",
      "bbq_grill",
      "patio",
      "workspace",
      "smoke_alarm",
    ],
    blocked: [
      [9, 18],
      [41, 48],
    ],
    listedDaysAgo: 528,
    updatedDaysAgo: 23,
  },
  {
    id: "prop-022",
    title: "Boulder Retreat Cabin at the Park's North Entrance",
    description:
      "A low-slung cabin built into the boulders, with a shaded porch, outdoor soaking tub, and the park entrance four minutes away.",
    propertyType: "cabin",
    pricePerNight: 214,
    cleaningFee: 95,
    ratingAverage: 4.88,
    ratingCount: 87,
    minNights: 2,
    isInstantBook: true,
    isRareFind: false,
    hostId: "host-119",
    coordinates: { lat: 34.1858, lng: -116.205 },
    street: "7455 Park Blvd",
    city: "Joshua Tree",
    state: "CA",
    zipCode: "92252",
    neighborhood: "North Entrance",
    capacity: { maxGuests: 5, bedrooms: 2, beds: 3, bathrooms: 1 },
    amenities: [
      "wifi",
      "kitchen",
      "air_conditioning",
      "heating",
      "free_parking",
      "bbq_grill",
      "patio",
      "pets_allowed",
      "smoke_alarm",
    ],
    blocked: [
      [3, 10],
      [24, 30],
    ],
    listedDaysAgo: 302,
    updatedDaysAgo: 27,
  },
  {
    id: "prop-023",
    title: "Desert Casita Studio with Outdoor Soaking Tub",
    description:
      "A walled casita with a private courtyard, plunge pool, and an outdoor tub positioned for sunrise over the San Jacintos.",
    propertyType: "studio",
    pricePerNight: 165,
    cleaningFee: 70,
    ratingAverage: 4.83,
    ratingCount: 112,
    minNights: 1,
    isInstantBook: true,
    isRareFind: false,
    hostId: "host-120",
    coordinates: { lat: 33.848, lng: -116.52 },
    street: "445 S Indian Canyon Dr Unit 2",
    city: "Palm Springs",
    state: "CA",
    zipCode: "92262",
    neighborhood: "Movie Colony",
    capacity: { maxGuests: 2, bedrooms: 0, beds: 1, bathrooms: 1 },
    amenities: [
      "wifi",
      "kitchen",
      "air_conditioning",
      "pool",
      "patio",
      "free_parking",
      "workspace",
      "smoke_alarm",
    ],
    blocked: [
      [4, 8],
      [21, 28],
    ],
    listedDaysAgo: 231,
    updatedDaysAgo: 3,
  },
  {
    id: "prop-024",
    title: "Rancho Mirage Lakefront Townhouse with Tennis",
    description:
      "A gated lakefront townhouse with two patios, resort pools, tennis courts, and a short drive to the El Paseo galleries.",
    propertyType: "townhouse",
    pricePerNight: 305,
    cleaningFee: 130,
    ratingAverage: 4.9,
    ratingCount: 76,
    minNights: 3,
    isInstantBook: false,
    isRareFind: false,
    hostId: "host-121",
    coordinates: { lat: 33.7397, lng: -116.412 },
    street: "69840 Frank Sinatra Dr Unit 21",
    city: "Rancho Mirage",
    state: "CA",
    zipCode: "92270",
    neighborhood: "Rancho Mirage",
    capacity: { maxGuests: 6, bedrooms: 3, beds: 3, bathrooms: 2.5 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "dryer",
      "air_conditioning",
      "pool",
      "free_parking",
      "patio",
      "lake_access",
      "gym",
      "smoke_alarm",
    ],
    blocked: [
      [8, 15],
      [34, 42],
    ],
    listedDaysAgo: 388,
    updatedDaysAgo: 29,
  },

  /* ------------------------------ San Francisco --------------------------- */
  {
    id: "prop-025",
    title: "Nob Hill Apartment with Cable Car Views",
    description:
      "A bay-window apartment on the cable car line, with a marble fireplace, original molding, and Grace Cathedral two blocks up the hill.",
    propertyType: "apartment",
    pricePerNight: 295,
    cleaningFee: 110,
    ratingAverage: 4.9,
    ratingCount: 158,
    minNights: 2,
    isInstantBook: true,
    isRareFind: false,
    hostId: "host-102",
    coordinates: { lat: 37.793, lng: -122.416 },
    street: "1050 Mason St Apt 5",
    city: "San Francisco",
    state: "CA",
    zipCode: "94108",
    neighborhood: "Nob Hill",
    capacity: { maxGuests: 3, bedrooms: 1, beds: 2, bathrooms: 1 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "dryer",
      "heating",
      "workspace",
      "smoke_alarm",
    ],
    blocked: [
      [6, 13],
      [32, 38],
    ],
    listedDaysAgo: 415,
    updatedDaysAgo: 31,
  },
  {
    id: "prop-026",
    title: "Mission District Studio with Murals at the Doorstep",
    description:
      "A bright rear studio overlooking a shared garden, surrounded by the neighborhood's best taquerias, bakeries, and mural alleys.",
    propertyType: "studio",
    pricePerNight: 175,
    cleaningFee: 65,
    ratingAverage: 4.76,
    ratingCount: 196,
    minNights: 1,
    isInstantBook: true,
    isRareFind: false,
    hostId: "host-122",
    coordinates: { lat: 37.7599, lng: -122.4148 },
    street: "2914 24th St Unit B",
    city: "San Francisco",
    state: "CA",
    zipCode: "94110",
    neighborhood: "Mission District",
    capacity: { maxGuests: 2, bedrooms: 0, beds: 1, bathrooms: 1 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "heating",
      "workspace",
      "smoke_alarm",
    ],
    blocked: [
      [2, 7],
      [19, 25],
    ],
    listedDaysAgo: 189,
    updatedDaysAgo: 22,
  },
  {
    id: "prop-027",
    title: "Sausalito Houseboat with Bay Bridge Sunsets",
    description:
      "A floating home in Waldo Point Harbor with a rooftop deck, wood-burning stove, and a ferry ride from downtown San Francisco.",
    propertyType: "house",
    pricePerNight: 385,
    cleaningFee: 150,
    ratingAverage: 4.95,
    ratingCount: 121,
    minNights: 2,
    isInstantBook: false,
    isRareFind: true,
    hostId: "host-123",
    coordinates: { lat: 37.8591, lng: -122.4853 },
    street: "62 Gate 6 Rd",
    city: "Sausalito",
    state: "CA",
    zipCode: "94965",
    neighborhood: "Waldo Point Harbor",
    capacity: { maxGuests: 4, bedrooms: 2, beds: 2, bathrooms: 1 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "dryer",
      "heating",
      "patio",
      "free_parking",
      "workspace",
      "smoke_alarm",
    ],
    blocked: [
      [7, 15],
      [29, 36],
    ],
    listedDaysAgo: 462,
    updatedDaysAgo: 24,
  },
  {
    id: "prop-028",
    title: "Berkeley Elmwood Townhouse Near Campus",
    description:
      "A quiet two-level townhouse with a private patio, garage parking, and College Avenue shops and cafés at the end of the block.",
    propertyType: "townhouse",
    pricePerNight: 258,
    cleaningFee: 100,
    ratingAverage: 4.85,
    ratingCount: 93,
    minNights: 2,
    isInstantBook: true,
    isRareFind: false,
    hostId: "host-124",
    coordinates: { lat: 37.857, lng: -122.254 },
    street: "2731 College Ave Unit 3",
    city: "Berkeley",
    state: "CA",
    zipCode: "94705",
    neighborhood: "Elmwood",
    capacity: { maxGuests: 5, bedrooms: 2, beds: 3, bathrooms: 1.5 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "dryer",
      "heating",
      "free_parking",
      "patio",
      "workspace",
      "smoke_alarm",
    ],
    blocked: [
      [5, 11],
      [26, 32],
    ],
    listedDaysAgo: 298,
    updatedDaysAgo: 30,
  },
  {
    id: "prop-029",
    title: "Sea Ranch Bluff Cabin Along the Coastal Trail",
    description:
      "A weathered-cedar cabin on the bluff with a sheep-grazed meadow, private trail access, and whale-watching from the living room.",
    propertyType: "cabin",
    pricePerNight: 340,
    cleaningFee: 145,
    ratingAverage: 4.97,
    ratingCount: 102,
    minNights: 2,
    isInstantBook: false,
    isRareFind: true,
    hostId: "host-111",
    coordinates: { lat: 38.715, lng: -123.428 },
    street: "355 Sea Walk Dr",
    city: "Sea Ranch",
    state: "CA",
    zipCode: "95497",
    neighborhood: "Sea Ranch",
    capacity: { maxGuests: 4, bedrooms: 2, beds: 2, bathrooms: 1 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "dryer",
      "heating",
      "free_parking",
      "patio",
      "bbq_grill",
      "workspace",
      "pets_allowed",
      "smoke_alarm",
    ],
    blocked: [
      [10, 17],
      [39, 46],
    ],
    listedDaysAgo: 507,
    updatedDaysAgo: 25,
  },

  /* -------------------------------- New York ------------------------------ */
  {
    id: "prop-030",
    title: "SoHo Cast-Iron Loft with Gallery Windows",
    description:
      "Eleven-foot tin ceilings, original maple floors, and six oversized windows above the cobblestones of Greene Street.",
    propertyType: "loft",
    pricePerNight: 425,
    cleaningFee: 165,
    ratingAverage: 4.92,
    ratingCount: 204,
    minNights: 2,
    isInstantBook: true,
    isRareFind: false,
    hostId: "host-104",
    coordinates: { lat: 40.7233, lng: -74.003 },
    street: "112 Greene St Unit 4F",
    city: "New York",
    state: "NY",
    zipCode: "10012",
    neighborhood: "SoHo",
    capacity: { maxGuests: 4, bedrooms: 1, beds: 2, bathrooms: 1.5 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "dryer",
      "air_conditioning",
      "heating",
      "gym",
      "workspace",
      "smoke_alarm",
    ],
    blocked: [
      [3, 10],
      [24, 31],
    ],
    listedDaysAgo: 536,
    updatedDaysAgo: 28,
  },
  {
    id: "prop-031",
    title: "Brooklyn Brownstone Triplex with Garden",
    description:
      "A landmarked Bed-Stuy brownstone with three floors, a landscaped garden, and a parlor floor made for long dinners.",
    propertyType: "townhouse",
    pricePerNight: 520,
    cleaningFee: 200,
    ratingAverage: 4.96,
    ratingCount: 137,
    minNights: 3,
    isInstantBook: false,
    isRareFind: true,
    hostId: "host-104",
    coordinates: { lat: 40.68, lng: -73.944 },
    street: "415 Putnam Ave",
    city: "Brooklyn",
    state: "NY",
    zipCode: "11216",
    neighborhood: "Bedford-Stuyvesant",
    capacity: { maxGuests: 8, bedrooms: 4, beds: 5, bathrooms: 2.5 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "dryer",
      "air_conditioning",
      "heating",
      "patio",
      "bbq_grill",
      "workspace",
      "smoke_alarm",
    ],
    blocked: [
      [8, 16],
      [35, 43],
    ],
    listedDaysAgo: 592,
    updatedDaysAgo: 34,
  },
  {
    id: "prop-032",
    title: "Williamsburg Apartment Steps from the Ferry",
    description:
      "A corner one-bedroom with skyline views, a full gym in the building, and the North Williamsburg ferry landing one block away.",
    propertyType: "apartment",
    pricePerNight: 235,
    cleaningFee: 90,
    ratingAverage: 4.8,
    ratingCount: 167,
    minNights: 1,
    isInstantBook: true,
    isRareFind: false,
    hostId: "host-102",
    coordinates: { lat: 40.714, lng: -73.957 },
    street: "120 N 6th St Apt 3C",
    city: "Brooklyn",
    state: "NY",
    zipCode: "11249",
    neighborhood: "Williamsburg",
    capacity: { maxGuests: 3, bedrooms: 1, beds: 2, bathrooms: 1 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "air_conditioning",
      "heating",
      "gym",
      "workspace",
      "smoke_alarm",
    ],
    blocked: [
      [4, 9],
      [22, 29],
    ],
    listedDaysAgo: 244,
    updatedDaysAgo: 2,
  },
  {
    id: "prop-033",
    title: "Catskills Creek-Side Cabin with Wood Stove",
    description:
      "A renovated hunting cabin on a trout creek, with a wood stove, screened porch, and fire pit under a canopy of hemlocks.",
    propertyType: "cabin",
    pricePerNight: 245,
    cleaningFee: 105,
    ratingAverage: 4.93,
    ratingCount: 88,
    minNights: 2,
    isInstantBook: true,
    isRareFind: false,
    hostId: "host-109",
    coordinates: { lat: 42.109, lng: -74.512 },
    street: "1180 Route 42",
    city: "Shandaken",
    state: "NY",
    zipCode: "12480",
    neighborhood: "Catskills",
    capacity: { maxGuests: 6, bedrooms: 3, beds: 4, bathrooms: 2 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "dryer",
      "heating",
      "hot_tub",
      "free_parking",
      "bbq_grill",
      "patio",
      "pets_allowed",
      "smoke_alarm",
    ],
    blocked: [
      [6, 12],
      [28, 34],
    ],
    listedDaysAgo: 356,
    updatedDaysAgo: 32,
  },
  {
    id: "prop-034",
    title: "Chelsea Garden Studio Near the High Line",
    description:
      "A garden-level studio with a private patio, sleeping alcove, and the High Line entrance half a block from the front door.",
    propertyType: "studio",
    pricePerNight: 210,
    cleaningFee: 85,
    ratingAverage: 4.74,
    ratingCount: 142,
    minNights: 1,
    isInstantBook: true,
    isRareFind: false,
    hostId: "host-122",
    coordinates: { lat: 40.7465, lng: -74.0014 },
    street: "446 W 25th St Unit 1R",
    city: "New York",
    state: "NY",
    zipCode: "10001",
    neighborhood: "Chelsea",
    capacity: { maxGuests: 2, bedrooms: 0, beds: 1, bathrooms: 1 },
    amenities: [
      "wifi",
      "kitchen",
      "air_conditioning",
      "heating",
      "patio",
      "workspace",
      "smoke_alarm",
    ],
    blocked: [
      [2, 6],
      [18, 24],
    ],
    listedDaysAgo: 176,
    updatedDaysAgo: 1,
  },
  {
    id: "prop-035",
    title: "Montauk Dune House with Heated Pool",
    description:
      "A cedar-shingled dune house with a heated gunite pool, outdoor shower, and a five-minute walk to Ditch Plains surf.",
    propertyType: "house",
    pricePerNight: 780,
    cleaningFee: 280,
    ratingAverage: 4.98,
    ratingCount: 64,
    minNights: 3,
    isInstantBook: false,
    isRareFind: true,
    hostId: "host-123",
    coordinates: { lat: 41.0462, lng: -71.952 },
    street: "32 Ditch Plains Rd",
    city: "Montauk",
    state: "NY",
    zipCode: "11954",
    neighborhood: "Ditch Plains",
    capacity: { maxGuests: 8, bedrooms: 4, beds: 5, bathrooms: 3 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "dryer",
      "air_conditioning",
      "heating",
      "pool",
      "hot_tub",
      "free_parking",
      "bbq_grill",
      "patio",
      "workspace",
      "smoke_alarm",
    ],
    blocked: [
      [11, 21],
      [44, 52],
    ],
    listedDaysAgo: 611,
    updatedDaysAgo: 35,
  },

  /* ---------------------------- Miami & The Keys -------------------------- */
  {
    id: "prop-036",
    title: "South Beach Art Deco Apartment One Block to Ocean Drive",
    description:
      "A restored Deco apartment with terrazzo floors, a rooftop pool, and the beach path one block east.",
    propertyType: "apartment",
    pricePerNight: 215,
    cleaningFee: 85,
    ratingAverage: 4.81,
    ratingCount: 258,
    minNights: 1,
    isInstantBook: true,
    isRareFind: false,
    hostId: "host-110",
    coordinates: { lat: 25.782, lng: -80.132 },
    street: "1050 Collins Ave Apt 604",
    city: "Miami Beach",
    state: "FL",
    zipCode: "33139",
    neighborhood: "South Beach",
    capacity: { maxGuests: 3, bedrooms: 1, beds: 2, bathrooms: 1 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "air_conditioning",
      "pool",
      "gym",
      "workspace",
      "smoke_alarm",
    ],
    blocked: [
      [3, 8],
      [21, 27],
    ],
    listedDaysAgo: 268,
    updatedDaysAgo: 6,
  },
  {
    id: "prop-037",
    title: "Wynwood Mural Loft with Rooftop Lounge",
    description:
      "A concrete loft in a converted warehouse with a shared rooftop, gallery walls, and the Wynwood Walls across the street.",
    propertyType: "loft",
    pricePerNight: 189,
    cleaningFee: 75,
    ratingAverage: 4.86,
    ratingCount: 174,
    minNights: 1,
    isInstantBook: true,
    isRareFind: false,
    hostId: "host-110",
    coordinates: { lat: 25.801, lng: -80.199 },
    street: "250 NW 24th St Unit 5",
    city: "Miami",
    state: "FL",
    zipCode: "33127",
    neighborhood: "Wynwood",
    capacity: { maxGuests: 3, bedrooms: 1, beds: 2, bathrooms: 1 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "dryer",
      "air_conditioning",
      "gym",
      "pool",
      "patio",
      "workspace",
      "smoke_alarm",
    ],
    blocked: [
      [5, 11],
      [26, 32],
    ],
    listedDaysAgo: 233,
    updatedDaysAgo: 9,
  },
  {
    id: "prop-038",
    title: "Key West Conch House with Wraparound Porch",
    description:
      "A restored conch house on a quiet Old Town lane with a wraparound porch, plunge pool, and two beach cruisers in the shed.",
    propertyType: "house",
    pricePerNight: 395,
    cleaningFee: 155,
    ratingAverage: 4.95,
    ratingCount: 149,
    minNights: 3,
    isInstantBook: false,
    isRareFind: true,
    hostId: "host-121",
    coordinates: { lat: 24.555, lng: -81.78 },
    street: "1216 Olivia St",
    city: "Key West",
    state: "FL",
    zipCode: "33040",
    neighborhood: "Old Town",
    capacity: { maxGuests: 6, bedrooms: 3, beds: 3, bathrooms: 2 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "dryer",
      "air_conditioning",
      "pool",
      "free_parking",
      "patio",
      "bbq_grill",
      "workspace",
      "pets_allowed",
      "smoke_alarm",
    ],
    blocked: [
      [7, 16],
      [33, 41],
    ],
    listedDaysAgo: 483,
    updatedDaysAgo: 36,
  },
  {
    id: "prop-039",
    title: "Miami Beach Waterfront Villa with Dock",
    description:
      "A gated Sunset Islands villa with eighty feet of water frontage, a heated pool, summer kitchen, and a dock for a 60-foot yacht.",
    propertyType: "villa",
    pricePerNight: 1180,
    cleaningFee: 340,
    ratingAverage: 4.99,
    ratingCount: 58,
    minNights: 4,
    isInstantBook: false,
    isRareFind: true,
    hostId: "host-101",
    coordinates: { lat: 25.793, lng: -80.142 },
    street: "4400 N Bay Rd",
    city: "Miami Beach",
    state: "FL",
    zipCode: "33140",
    neighborhood: "Sunset Islands",
    capacity: { maxGuests: 10, bedrooms: 5, beds: 6, bathrooms: 4.5 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "dryer",
      "air_conditioning",
      "pool",
      "hot_tub",
      "gym",
      "free_parking",
      "ev_charger",
      "bbq_grill",
      "patio",
      "workspace",
      "smoke_alarm",
    ],
    blocked: [
      [12, 24],
      [47, 56],
    ],
    listedDaysAgo: 645,
    updatedDaysAgo: 37,
  },
  {
    id: "prop-040",
    title: "Islamorada Bayfront Cabin with Kayaks",
    description:
      "A low-key bayfront cabin with a private sandy beach, two kayaks, a fish-cleaning table, and sunset views over Florida Bay.",
    propertyType: "cabin",
    pricePerNight: 265,
    cleaningFee: 115,
    ratingAverage: 4.88,
    ratingCount: 97,
    minNights: 2,
    isInstantBook: true,
    isRareFind: false,
    hostId: "host-121",
    coordinates: { lat: 24.924, lng: -80.628 },
    street: "79801 Overseas Hwy",
    city: "Islamorada",
    state: "FL",
    zipCode: "33036",
    neighborhood: "Upper Matecumbe Key",
    capacity: { maxGuests: 5, bedrooms: 2, beds: 3, bathrooms: 1.5 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "air_conditioning",
      "free_parking",
      "patio",
      "lake_access",
      "bbq_grill",
      "pets_allowed",
      "smoke_alarm",
    ],
    blocked: [
      [4, 12],
      [30, 37],
    ],
    listedDaysAgo: 374,
    updatedDaysAgo: 38,
  },

  /* --------------------------------- Austin ------------------------------- */
  {
    id: "prop-041",
    title: "East Austin Bungalow with Shaded Backyard Bar",
    description:
      "A 1940s bungalow with a screened porch, outdoor bar, string lights, and the best of East Sixth within walking distance.",
    propertyType: "house",
    pricePerNight: 195,
    cleaningFee: 85,
    ratingAverage: 4.89,
    ratingCount: 211,
    minNights: 2,
    isInstantBook: true,
    isRareFind: false,
    hostId: "host-106",
    coordinates: { lat: 30.262, lng: -97.725 },
    street: "1808 E 7th St",
    city: "Austin",
    state: "TX",
    zipCode: "78702",
    neighborhood: "East Austin",
    capacity: { maxGuests: 5, bedrooms: 2, beds: 3, bathrooms: 1.5 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "dryer",
      "air_conditioning",
      "heating",
      "free_parking",
      "bbq_grill",
      "patio",
      "workspace",
      "pets_allowed",
      "smoke_alarm",
    ],
    blocked: [
      [6, 12],
      [27, 33],
    ],
    listedDaysAgo: 322,
    updatedDaysAgo: 39,
  },
  {
    id: "prop-042",
    title: "Rainey Street High-Rise Apartment with Skyline View",
    description:
      "An eighteenth-floor apartment above the Rainey Street bungalow bars, with a pool deck and a view straight down the lake.",
    propertyType: "apartment",
    pricePerNight: 172,
    cleaningFee: 70,
    ratingAverage: 4.78,
    ratingCount: 184,
    minNights: 1,
    isInstantBook: true,
    isRareFind: false,
    hostId: "host-118",
    coordinates: { lat: 30.259, lng: -97.739 },
    street: "88 Rainey St Apt 1802",
    city: "Austin",
    state: "TX",
    zipCode: "78701",
    neighborhood: "Rainey Street",
    capacity: { maxGuests: 3, bedrooms: 1, beds: 2, bathrooms: 1 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "dryer",
      "air_conditioning",
      "gym",
      "pool",
      "workspace",
      "smoke_alarm",
    ],
    blocked: [
      [2, 7],
      [23, 30],
    ],
    listedDaysAgo: 209,
    updatedDaysAgo: 5,
  },
  {
    id: "prop-043",
    title: "Hill Country Ranch House on Twelve Acres",
    description:
      "A limestone ranch house on twelve fenced acres with a spring-fed pool, covered patio, and long Hill Country sunsets.",
    propertyType: "house",
    pricePerNight: 385,
    cleaningFee: 160,
    ratingAverage: 4.96,
    ratingCount: 76,
    minNights: 3,
    isInstantBook: false,
    isRareFind: true,
    hostId: "host-124",
    coordinates: { lat: 30.312, lng: -98.241 },
    street: "2400 Ranch Road 12",
    city: "Dripping Springs",
    state: "TX",
    zipCode: "78620",
    neighborhood: "Dripping Springs",
    capacity: { maxGuests: 9, bedrooms: 4, beds: 6, bathrooms: 3 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "dryer",
      "air_conditioning",
      "heating",
      "pool",
      "hot_tub",
      "free_parking",
      "ev_charger",
      "bbq_grill",
      "patio",
      "workspace",
      "smoke_alarm",
    ],
    blocked: [
      [9, 18],
      [38, 46],
    ],
    listedDaysAgo: 519,
    updatedDaysAgo: 40,
  },
  {
    id: "prop-044",
    title: "South Congress Studio Above a Coffee Roastery",
    description:
      "A snug studio above a roastery with a balcony over South Congress, a queen bed, and espresso downstairs every morning.",
    propertyType: "studio",
    pricePerNight: 138,
    cleaningFee: 60,
    ratingAverage: 4.72,
    ratingCount: 129,
    minNights: 1,
    isInstantBook: true,
    isRareFind: false,
    hostId: "host-106",
    coordinates: { lat: 30.248, lng: -97.751 },
    street: "1601 S Congress Ave Unit 2",
    city: "Austin",
    state: "TX",
    zipCode: "78704",
    neighborhood: "South Congress",
    capacity: { maxGuests: 2, bedrooms: 0, beds: 1, bathrooms: 1 },
    amenities: [
      "wifi",
      "kitchen",
      "air_conditioning",
      "workspace",
      "smoke_alarm",
    ],
    blocked: [
      [3, 7],
      [20, 26],
    ],
    listedDaysAgo: 167,
    updatedDaysAgo: 41,
  },

  /* -------------------------------- Colorado ------------------------------ */
  {
    id: "prop-045",
    title: "Aspen Mountain Chalet with Private Hot Tub",
    description:
      "A timber chalet two blocks from the Silver Queen gondola with a stone fireplace, ski room, and hot tub under the aspens.",
    propertyType: "cabin",
    pricePerNight: 920,
    cleaningFee: 300,
    ratingAverage: 4.97,
    ratingCount: 88,
    minNights: 3,
    isInstantBook: false,
    isRareFind: true,
    hostId: "host-112",
    coordinates: { lat: 39.187, lng: -106.818 },
    street: "620 S Mill St",
    city: "Aspen",
    state: "CO",
    zipCode: "81611",
    neighborhood: "Aspen Core",
    capacity: { maxGuests: 8, bedrooms: 4, beds: 5, bathrooms: 3.5 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "dryer",
      "heating",
      "hot_tub",
      "ski_in_out",
      "free_parking",
      "ev_charger",
      "bbq_grill",
      "workspace",
      "smoke_alarm",
    ],
    blocked: [
      [10, 20],
      [43, 51],
    ],
    listedDaysAgo: 576,
    updatedDaysAgo: 42,
  },
  {
    id: "prop-046",
    title: "Vail Village Ski Townhouse Steps to Gondola One",
    description:
      "A Vail Village townhouse with heated garage parking, a riverside balcony, and Gondola One ninety steps from the door.",
    propertyType: "townhouse",
    pricePerNight: 640,
    cleaningFee: 240,
    ratingAverage: 4.94,
    ratingCount: 126,
    minNights: 3,
    isInstantBook: true,
    isRareFind: true,
    hostId: "host-117",
    coordinates: { lat: 39.64, lng: -106.374 },
    street: "260 E Meadow Dr Unit 8",
    city: "Vail",
    state: "CO",
    zipCode: "81657",
    neighborhood: "Vail Village",
    capacity: { maxGuests: 8, bedrooms: 3, beds: 5, bathrooms: 3 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "dryer",
      "heating",
      "hot_tub",
      "ski_in_out",
      "free_parking",
      "gym",
      "workspace",
      "smoke_alarm",
    ],
    blocked: [
      [6, 14],
      [31, 39],
    ],
    listedDaysAgo: 449,
    updatedDaysAgo: 43,
  },
  {
    id: "prop-047",
    title: "Breckenridge Timber Cabin on the Blue River",
    description:
      "A riverside cabin with a wood-burning fireplace, riverside hot tub, and a free shuttle stop at the end of the driveway.",
    propertyType: "cabin",
    pricePerNight: 385,
    cleaningFee: 155,
    ratingAverage: 4.91,
    ratingCount: 163,
    minNights: 2,
    isInstantBook: true,
    isRareFind: false,
    hostId: "host-117",
    coordinates: { lat: 39.481, lng: -106.038 },
    street: "415 S Park Ave",
    city: "Breckenridge",
    state: "CO",
    zipCode: "80424",
    neighborhood: "Blue River",
    capacity: { maxGuests: 7, bedrooms: 3, beds: 4, bathrooms: 2.5 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "dryer",
      "heating",
      "hot_tub",
      "lake_access",
      "free_parking",
      "bbq_grill",
      "patio",
      "pets_allowed",
      "smoke_alarm",
    ],
    blocked: [
      [5, 13],
      [29, 36],
    ],
    listedDaysAgo: 392,
    updatedDaysAgo: 44,
  },
  {
    id: "prop-048",
    title: "Telluride Mountain Loft with San Juan Views",
    description:
      "A top-floor loft on Colorado Avenue with a ski-storage locker, boxcar gondola access, and San Juan peaks filling every window.",
    propertyType: "loft",
    pricePerNight: 470,
    cleaningFee: 185,
    ratingAverage: 4.95,
    ratingCount: 91,
    minNights: 2,
    isInstantBook: true,
    isRareFind: false,
    hostId: "host-114",
    coordinates: { lat: 37.937, lng: -107.813 },
    street: "150 W Colorado Ave Unit 3",
    city: "Telluride",
    state: "CO",
    zipCode: "81320",
    neighborhood: "Telluride Historic District",
    capacity: { maxGuests: 4, bedrooms: 1, beds: 2, bathrooms: 1 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "heating",
      "hot_tub",
      "ski_in_out",
      "free_parking",
      "workspace",
      "smoke_alarm",
    ],
    blocked: [
      [8, 16],
      [34, 42],
    ],
    listedDaysAgo: 337,
    updatedDaysAgo: 45,
  },

  /* --------------------------------- Arizona ------------------------------ */
  {
    id: "prop-049",
    title: "Sedona Red Rock Villa with Vortex Views",
    description:
      "A stucco-and-glass villa facing Cathedral Rock with a negative-edge pool, outdoor fireplace, and a private trail to the vortex.",
    propertyType: "villa",
    pricePerNight: 575,
    cleaningFee: 230,
    ratingAverage: 4.98,
    ratingCount: 132,
    minNights: 3,
    isInstantBook: true,
    isRareFind: true,
    hostId: "host-120",
    coordinates: { lat: 34.8697, lng: -111.761 },
    street: "55 Schnebly Hill Rd",
    city: "Sedona",
    state: "AZ",
    zipCode: "86336",
    neighborhood: "Schnebly Hill",
    capacity: { maxGuests: 8, bedrooms: 4, beds: 5, bathrooms: 3 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "dryer",
      "air_conditioning",
      "heating",
      "pool",
      "hot_tub",
      "free_parking",
      "ev_charger",
      "bbq_grill",
      "patio",
      "workspace",
      "smoke_alarm",
    ],
    blocked: [
      [7, 15],
      [36, 44],
    ],
    listedDaysAgo: 541,
    updatedDaysAgo: 46,
  },
  {
    id: "prop-050",
    title: "Old Town Scottsdale Condo with Resort Pool",
    description:
      "A two-bedroom condo in a resort complex with three pools, a gym, and the galleries and bars of Old Town ten minutes on foot.",
    propertyType: "apartment",
    pricePerNight: 205,
    cleaningFee: 80,
    ratingAverage: 4.84,
    ratingCount: 197,
    minNights: 1,
    isInstantBook: true,
    isRareFind: false,
    hostId: "host-105",
    coordinates: { lat: 33.494, lng: -111.926 },
    street: "7210 E 1st Ave Unit 214",
    city: "Scottsdale",
    state: "AZ",
    zipCode: "85251",
    neighborhood: "Old Town",
    capacity: { maxGuests: 4, bedrooms: 2, beds: 2, bathrooms: 2 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "dryer",
      "air_conditioning",
      "pool",
      "hot_tub",
      "gym",
      "free_parking",
      "workspace",
      "smoke_alarm",
    ],
    blocked: [
      [4, 10],
      [25, 31],
    ],
    listedDaysAgo: 283,
    updatedDaysAgo: 47,
  },
  {
    id: "prop-051",
    title: "Sedona Canyon Casita with Outdoor Fireplace",
    description:
      "A single-level casita in Oak Creek Village with a walled courtyard, outdoor fireplace, and red-rock views from the patio.",
    propertyType: "house",
    pricePerNight: 295,
    cleaningFee: 120,
    ratingAverage: 4.9,
    ratingCount: 104,
    minNights: 2,
    isInstantBook: true,
    isRareFind: false,
    hostId: "host-120",
    coordinates: { lat: 34.848, lng: -111.789 },
    street: "300 Canyon Diablo Rd",
    city: "Sedona",
    state: "AZ",
    zipCode: "86351",
    neighborhood: "Village of Oak Creek",
    capacity: { maxGuests: 4, bedrooms: 2, beds: 3, bathrooms: 1 },
    amenities: [
      "wifi",
      "kitchen",
      "air_conditioning",
      "heating",
      "hot_tub",
      "free_parking",
      "patio",
      "bbq_grill",
      "workspace",
      "smoke_alarm",
    ],
    blocked: [
      [6, 12],
      [28, 35],
    ],
    listedDaysAgo: 308,
    updatedDaysAgo: 48,
  },
  {
    id: "prop-052",
    title: "Tempe Mill Avenue Studio Near the Lake",
    description:
      "A furnished studio a block from Mill Avenue with a resort pool, a gym, and the Tempe Town Lake path three minutes away.",
    propertyType: "studio",
    pricePerNight: 118,
    cleaningFee: 50,
    ratingAverage: 4.69,
    ratingCount: 151,
    minNights: 1,
    isInstantBook: true,
    isRareFind: false,
    hostId: "host-114",
    coordinates: { lat: 33.425, lng: -111.94 },
    street: "5 E 6th St Unit 408",
    city: "Tempe",
    state: "AZ",
    zipCode: "85281",
    neighborhood: "Mill Avenue District",
    capacity: { maxGuests: 2, bedrooms: 0, beds: 1, bathrooms: 1 },
    amenities: [
      "wifi",
      "kitchen",
      "air_conditioning",
      "pool",
      "gym",
      "workspace",
      "smoke_alarm",
    ],
    blocked: [
      [2, 6],
      [19, 25],
    ],
    listedDaysAgo: 176,
    updatedDaysAgo: 49,
  },

  /* ---------------------------- Pacific Northwest ------------------------- */
  {
    id: "prop-053",
    title: "Capitol Hill Loft Above Volunteer Park",
    description:
      "A one-bedroom loft with exposed brick, a sleeping mezzanine, and Volunteer Park's conservatory three blocks up the hill.",
    propertyType: "loft",
    pricePerNight: 195,
    cleaningFee: 80,
    ratingAverage: 4.85,
    ratingCount: 178,
    minNights: 1,
    isInstantBook: true,
    isRareFind: false,
    hostId: "host-119",
    coordinates: { lat: 47.63, lng: -122.317 },
    street: "1420 12th Ave Unit 3",
    city: "Seattle",
    state: "WA",
    zipCode: "98122",
    neighborhood: "Capitol Hill",
    capacity: { maxGuests: 3, bedrooms: 1, beds: 1, bathrooms: 1 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "dryer",
      "heating",
      "workspace",
      "smoke_alarm",
    ],
    blocked: [
      [5, 10],
      [24, 30],
    ],
    listedDaysAgo: 251,
    updatedDaysAgo: 50,
  },
  {
    id: "prop-054",
    title: "Ballard Townhouse with Rooftop Sound Views",
    description:
      "A three-level townhouse with a rooftop deck facing the Sound, a two-car garage, and the Ballard Locks a short bike ride away.",
    propertyType: "townhouse",
    pricePerNight: 268,
    cleaningFee: 110,
    ratingAverage: 4.9,
    ratingCount: 112,
    minNights: 2,
    isInstantBook: true,
    isRareFind: false,
    hostId: "host-103",
    coordinates: { lat: 47.669, lng: -122.386 },
    street: "6512 24th Ave NW",
    city: "Seattle",
    state: "WA",
    zipCode: "98107",
    neighborhood: "Ballard",
    capacity: { maxGuests: 5, bedrooms: 2, beds: 3, bathrooms: 1.5 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "dryer",
      "heating",
      "free_parking",
      "ev_charger",
      "patio",
      "workspace",
      "smoke_alarm",
    ],
    blocked: [
      [7, 13],
      [30, 37],
    ],
    listedDaysAgo: 329,
    updatedDaysAgo: 51,
  },
  {
    id: "prop-055",
    title: "Cannon Beach Cabin with Haystack Rock Views",
    description:
      "A shingled cabin two streets from the sand with a wood stove, cedar hot tub, and Haystack Rock framed by the picture window.",
    propertyType: "cabin",
    pricePerNight: 315,
    cleaningFee: 130,
    ratingAverage: 4.95,
    ratingCount: 146,
    minNights: 2,
    isInstantBook: true,
    isRareFind: true,
    hostId: "host-111",
    coordinates: { lat: 45.891, lng: -123.962 },
    street: "240 W Gower Ave",
    city: "Cannon Beach",
    state: "OR",
    zipCode: "97110",
    neighborhood: "Cannon Beach",
    capacity: { maxGuests: 6, bedrooms: 3, beds: 4, bathrooms: 2 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "dryer",
      "heating",
      "free_parking",
      "bbq_grill",
      "patio",
      "workspace",
      "pets_allowed",
      "smoke_alarm",
    ],
    blocked: [
      [9, 16],
      [35, 42],
    ],
    listedDaysAgo: 424,
    updatedDaysAgo: 52,
  },
  {
    id: "prop-056",
    title: "Bend Riverfront Studio with Deschutes Access",
    description:
      "A ground-floor studio backing onto the Deschutes River trail, with cruiser bikes, a fire pit, and the Old Mill two miles east.",
    propertyType: "studio",
    pricePerNight: 145,
    cleaningFee: 60,
    ratingAverage: 4.77,
    ratingCount: 89,
    minNights: 1,
    isInstantBook: true,
    isRareFind: false,
    hostId: "host-103",
    coordinates: { lat: 44.059, lng: -121.315 },
    street: "550 NW Wall St Unit 5",
    city: "Bend",
    state: "OR",
    zipCode: "97703",
    neighborhood: "River West",
    capacity: { maxGuests: 2, bedrooms: 0, beds: 1, bathrooms: 1 },
    amenities: [
      "wifi",
      "kitchen",
      "heating",
      "air_conditioning",
      "lake_access",
      "free_parking",
      "workspace",
      "smoke_alarm",
    ],
    blocked: [
      [3, 8],
      [22, 28],
    ],
    listedDaysAgo: 192,
    updatedDaysAgo: 53,
  },
  {
    id: "prop-057",
    title: "Pearl District Apartment with Private Terrace",
    description:
      "A two-bedroom apartment with a wrap terrace above the Pearl's galleries, plus a gym, rooftop lounge, and deeded parking.",
    propertyType: "apartment",
    pricePerNight: 225,
    cleaningFee: 90,
    ratingAverage: 4.87,
    ratingCount: 163,
    minNights: 2,
    isInstantBook: true,
    isRareFind: false,
    hostId: "host-122",
    coordinates: { lat: 45.527, lng: -122.682 },
    street: "1230 NW Hoyt St Apt 902",
    city: "Portland",
    state: "OR",
    zipCode: "97209",
    neighborhood: "Pearl District",
    capacity: { maxGuests: 4, bedrooms: 2, beds: 2, bathrooms: 1 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "dryer",
      "heating",
      "air_conditioning",
      "gym",
      "patio",
      "workspace",
      "smoke_alarm",
    ],
    blocked: [
      [6, 12],
      [27, 34],
    ],
    listedDaysAgo: 288,
    updatedDaysAgo: 54,
  },

  /* --------------------------- Nashville & Smokies ------------------------ */
  {
    id: "prop-058",
    title: "East Nashville Craftsman with Songwriter Studio",
    description:
      "A craftsman bungalow with a converted garage studio, screened porch, and Five Points' bars and coffee shops on foot.",
    propertyType: "house",
    pricePerNight: 235,
    cleaningFee: 95,
    ratingAverage: 4.91,
    ratingCount: 188,
    minNights: 2,
    isInstantBook: true,
    isRareFind: false,
    hostId: "host-116",
    coordinates: { lat: 36.183, lng: -86.735 },
    street: "1108 Woodland St",
    city: "Nashville",
    state: "TN",
    zipCode: "37206",
    neighborhood: "East Nashville",
    capacity: { maxGuests: 6, bedrooms: 3, beds: 4, bathrooms: 2 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "dryer",
      "air_conditioning",
      "heating",
      "free_parking",
      "bbq_grill",
      "patio",
      "workspace",
      "pets_allowed",
      "smoke_alarm",
    ],
    blocked: [
      [5, 11],
      [26, 33],
    ],
    listedDaysAgo: 345,
    updatedDaysAgo: 55,
  },
  {
    id: "prop-059",
    title: "Downtown Nashville High-Rise with Rooftop Pool",
    description:
      "A sixteenth-floor apartment in The Gulch with a rooftop pool, skyline views, and Lower Broadway twelve minutes on foot.",
    propertyType: "apartment",
    pricePerNight: 198,
    cleaningFee: 80,
    ratingAverage: 4.8,
    ratingCount: 242,
    minNights: 1,
    isInstantBook: true,
    isRareFind: false,
    hostId: "host-105",
    coordinates: { lat: 36.162, lng: -86.779 },
    street: "315 Union St Apt 1604",
    city: "Nashville",
    state: "TN",
    zipCode: "37201",
    neighborhood: "The Gulch",
    capacity: { maxGuests: 3, bedrooms: 1, beds: 2, bathrooms: 1 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "dryer",
      "air_conditioning",
      "gym",
      "pool",
      "workspace",
      "smoke_alarm",
    ],
    blocked: [
      [3, 9],
      [24, 30],
    ],
    listedDaysAgo: 226,
    updatedDaysAgo: 56,
  },
  {
    id: "prop-060",
    title: "Smoky Mountain Cabin with Mountain-View Hot Tub",
    description:
      "A log cabin above Wears Valley with a hot tub facing the Smokies, a game loft, and the national park boundary a mile up the road.",
    propertyType: "cabin",
    pricePerNight: 265,
    cleaningFee: 115,
    ratingAverage: 4.93,
    ratingCount: 214,
    minNights: 2,
    isInstantBook: true,
    isRareFind: true,
    hostId: "host-116",
    coordinates: { lat: 35.714, lng: -83.51 },
    street: "3410 Wears Valley Rd",
    city: "Sevierville",
    state: "TN",
    zipCode: "37862",
    neighborhood: "Wears Valley",
    capacity: { maxGuests: 7, bedrooms: 3, beds: 4, bathrooms: 2 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "dryer",
      "heating",
      "air_conditioning",
      "hot_tub",
      "free_parking",
      "bbq_grill",
      "patio",
      "workspace",
      "smoke_alarm",
    ],
    blocked: [
      [7, 15],
      [32, 40],
    ],
    listedDaysAgo: 411,
    updatedDaysAgo: 57,
  },
  {
    id: "prop-061",
    title: "Music Row Studio with Vintage Vinyl Wall",
    description:
      "A compact studio beside the historic studios of Music Row, with a vinyl wall, turntable, and Belmont cafés around the corner.",
    propertyType: "studio",
    pricePerNight: 148,
    cleaningFee: 60,
    ratingAverage: 4.73,
    ratingCount: 126,
    minNights: 1,
    isInstantBook: true,
    isRareFind: false,
    hostId: "host-122",
    coordinates: { lat: 36.152, lng: -86.793 },
    street: "1010 16th Ave S Unit 6",
    city: "Nashville",
    state: "TN",
    zipCode: "37212",
    neighborhood: "Music Row",
    capacity: { maxGuests: 2, bedrooms: 0, beds: 1, bathrooms: 1 },
    amenities: [
      "wifi",
      "kitchen",
      "air_conditioning",
      "heating",
      "workspace",
      "smoke_alarm",
    ],
    blocked: [
      [2, 5],
      [18, 23],
    ],
    listedDaysAgo: 158,
    updatedDaysAgo: 58,
  },

  /* ------------------------------ Napa & Sonoma --------------------------- */
  {
    id: "prop-062",
    title: "Napa Valley Vineyard Villa with Tasting Deck",
    description:
      "A villa at the edge of a working cabernet vineyard, with a stone tasting deck, pool, and chef's kitchen for harvest dinners.",
    propertyType: "villa",
    pricePerNight: 880,
    cleaningFee: 295,
    ratingAverage: 4.99,
    ratingCount: 93,
    minNights: 3,
    isInstantBook: false,
    isRareFind: true,
    hostId: "host-101",
    coordinates: { lat: 38.402, lng: -122.36 },
    street: "1155 Oakville Grade",
    city: "Oakville",
    state: "CA",
    zipCode: "94562",
    neighborhood: "Oakville",
    capacity: { maxGuests: 8, bedrooms: 4, beds: 5, bathrooms: 4 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "dryer",
      "air_conditioning",
      "heating",
      "pool",
      "hot_tub",
      "free_parking",
      "ev_charger",
      "bbq_grill",
      "patio",
      "workspace",
      "smoke_alarm",
    ],
    blocked: [
      [8, 18],
      [40, 48],
    ],
    listedDaysAgo: 598,
    updatedDaysAgo: 59,
  },
  {
    id: "prop-063",
    title: "Sonoma Plaza Cottage with Rose Garden",
    description:
      "A cottage two blocks from Sonoma Plaza with a rose garden, bocce court, and a kitchen built around the Saturday farmers market.",
    propertyType: "house",
    pricePerNight: 375,
    cleaningFee: 150,
    ratingAverage: 4.94,
    ratingCount: 107,
    minNights: 2,
    isInstantBook: true,
    isRareFind: false,
    hostId: "host-107",
    coordinates: { lat: 38.293, lng: -122.458 },
    street: "415 First St E",
    city: "Sonoma",
    state: "CA",
    zipCode: "95476",
    neighborhood: "Sonoma Plaza",
    capacity: { maxGuests: 5, bedrooms: 2, beds: 3, bathrooms: 1.5 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "dryer",
      "air_conditioning",
      "heating",
      "free_parking",
      "patio",
      "bbq_grill",
      "workspace",
      "pets_allowed",
      "smoke_alarm",
    ],
    blocked: [
      [6, 13],
      [29, 35],
    ],
    listedDaysAgo: 366,
    updatedDaysAgo: 60,
  },
  {
    id: "prop-064",
    title: "Healdsburg Barn Loft Overlooking the Vineyards",
    description:
      "A converted hayloft in Dry Creek Valley with a cathedral ceiling, private deck over the vines, and tasting rooms down the road.",
    propertyType: "loft",
    pricePerNight: 425,
    cleaningFee: 170,
    ratingAverage: 4.96,
    ratingCount: 72,
    minNights: 2,
    isInstantBook: true,
    isRareFind: true,
    hostId: "host-109",
    coordinates: { lat: 38.612, lng: -122.869 },
    street: "3200 Westside Rd",
    city: "Healdsburg",
    state: "CA",
    zipCode: "95448",
    neighborhood: "Dry Creek Valley",
    capacity: { maxGuests: 4, bedrooms: 1, beds: 2, bathrooms: 1 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "air_conditioning",
      "heating",
      "hot_tub",
      "free_parking",
      "patio",
      "workspace",
      "smoke_alarm",
    ],
    blocked: [
      [10, 17],
      [37, 44],
    ],
    listedDaysAgo: 432,
    updatedDaysAgo: 61,
  },

  /* --------------------------------- Chicago ------------------------------ */
  {
    id: "prop-065",
    title: "Wicker Park Greystone Apartment with Bay Windows",
    description:
      "A greystone two-bedroom with bay windows, a decorative fireplace, and the Damen Blue Line stop a block from the door.",
    propertyType: "apartment",
    pricePerNight: 185,
    cleaningFee: 75,
    ratingAverage: 4.86,
    ratingCount: 206,
    minNights: 1,
    isInstantBook: true,
    isRareFind: false,
    hostId: "host-124",
    coordinates: { lat: 41.908, lng: -87.679 },
    street: "1420 N Damen Ave Apt 3",
    city: "Chicago",
    state: "IL",
    zipCode: "60622",
    neighborhood: "Wicker Park",
    capacity: { maxGuests: 4, bedrooms: 2, beds: 2, bathrooms: 1 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "dryer",
      "heating",
      "air_conditioning",
      "workspace",
      "smoke_alarm",
    ],
    blocked: [
      [4, 10],
      [25, 31],
    ],
    listedDaysAgo: 297,
    updatedDaysAgo: 62,
  },
  {
    id: "prop-066",
    title: "Lakeview High-Rise Loft with Lake Michigan Views",
    description:
      "A twenty-second-floor loft with a wall of windows facing the lake, an in-building gym, and the Lakefront Trail across the street.",
    propertyType: "loft",
    pricePerNight: 215,
    cleaningFee: 85,
    ratingAverage: 4.82,
    ratingCount: 175,
    minNights: 1,
    isInstantBook: true,
    isRareFind: false,
    hostId: "host-119",
    coordinates: { lat: 41.94, lng: -87.653 },
    street: "655 W Irving Park Rd Unit 2205",
    city: "Chicago",
    state: "IL",
    zipCode: "60613",
    neighborhood: "Lakeview",
    capacity: { maxGuests: 3, bedrooms: 1, beds: 1, bathrooms: 1 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "dryer",
      "heating",
      "air_conditioning",
      "gym",
      "workspace",
      "smoke_alarm",
    ],
    blocked: [
      [5, 11],
      [27, 33],
    ],
    listedDaysAgo: 262,
    updatedDaysAgo: 63,
  },
  {
    id: "prop-067",
    title: "Lincoln Park Townhouse Steps to the Conservatory",
    description:
      "A three-level townhouse facing the park with garage parking, a rooftop deck, and the Lincoln Park Zoo a five-minute walk north.",
    propertyType: "townhouse",
    pricePerNight: 285,
    cleaningFee: 120,
    ratingAverage: 4.89,
    ratingCount: 118,
    minNights: 2,
    isInstantBook: false,
    isRareFind: false,
    hostId: "host-118",
    coordinates: { lat: 41.921, lng: -87.636 },
    street: "2040 N Stockton Dr",
    city: "Chicago",
    state: "IL",
    zipCode: "60614",
    neighborhood: "Lincoln Park",
    capacity: { maxGuests: 6, bedrooms: 3, beds: 4, bathrooms: 2.5 },
    amenities: [
      "wifi",
      "kitchen",
      "washer",
      "dryer",
      "heating",
      "air_conditioning",
      "free_parking",
      "ev_charger",
      "patio",
      "workspace",
      "smoke_alarm",
    ],
    blocked: [
      [7, 14],
      [31, 38],
    ],
    listedDaysAgo: 351,
    updatedDaysAgo: 64,
  },
];

/* -------------------------------------------------------------------------- */
/* 4. Expansion into complete listings                                        */
/* -------------------------------------------------------------------------- */

const REVIEW_AXIS_BIAS: Record<keyof ReviewBreakdown, number> = {
  cleanliness: 0.02,
  accuracy: 0,
  communication: 0.03,
  location: 0.02,
  checkIn: 0.05,
  value: -0.07,
};

/** Deterministic per-axis review spread around the listing's headline rating. */
function deriveReviewScore(
  baseRating: number,
  axis: keyof ReviewBreakdown,
  listingId: string,
): number {
  const jitter = ((stableHash(`${listingId}:${axis}`) % 17) - 8) / 100;
  return clamp(roundTo(baseRating + REVIEW_AXIS_BIAS[axis] + jitter, 1), 1, 5);
}

function buildReviewBreakdown(
  baseRating: number,
  listingId: string,
): ReviewBreakdown {
  return {
    cleanliness: deriveReviewScore(baseRating, "cleanliness", listingId),
    accuracy: deriveReviewScore(baseRating, "accuracy", listingId),
    communication: deriveReviewScore(baseRating, "communication", listingId),
    location: deriveReviewScore(baseRating, "location", listingId),
    checkIn: deriveReviewScore(baseRating, "checkIn", listingId),
    value: deriveReviewScore(baseRating, "value", listingId),
  };
}

function buildHostProfile(definition: SeedHostDefinition): HostProfile {
  return {
    id: definition.id,
    name: definition.name,
    avatarUrl: avatarImage(definition.avatarPhotoId),
    isSuperhost: definition.isSuperhost,
    joinedDate: definition.joinedDate,
    responseRatePercent: definition.responseRatePercent,
    responseTimeMinutes: definition.responseTimeMinutes,
  };
}

function withTimeOfDay(date: Date, hour: number, minute: number): Date {
  return new Date(date.getTime() + hour * 3_600_000 + minute * 60_000);
}

/** Expands one compact definition into a fully validated `PropertyListing`. */
export function buildListingFromDefinition(
  definition: SeedListingDefinition,
  index: number,
  referenceDate: Date = new Date(),
): PropertyListing {
  const hostDefinition = HOSTS_BY_ID.get(definition.hostId);
  if (!hostDefinition) {
    throw new Error(
      `[seed-data] listing "${definition.id}" references unknown host "${definition.hostId}"`,
    );
  }

  const gallery = (
    definition.images ?? selectGallery(index, definition.pricePerNight)
  ).map((photoId) => propertyImage(photoId));

  const blockedRanges: AvailabilityRange[] = definition.blocked
    .map(([startOffsetDays, endOffsetDays]) => ({
      startDate: toIsoDateString(addDays(referenceDate, startOffsetDays)),
      endDate: toIsoDateString(addDays(referenceDate, endOffsetDays)),
    }))
    .sort((a, b) => a.startDate.localeCompare(b.startDate));

  const createdAt = toIsoDateTimeString(
    withTimeOfDay(
      addDays(referenceDate, -definition.listedDaysAgo),
      8 + (index % 6),
      (index * 7) % 60,
    ),
  );
  const updatedAt = toIsoDateTimeString(
    withTimeOfDay(
      addDays(referenceDate, -definition.updatedDaysAgo),
      9 + (index % 5),
      (index * 11) % 60,
    ),
  );

  return {
    id: definition.id,
    title: definition.title,
    slug: slugify(definition.title),
    description: definition.description,
    propertyType: definition.propertyType,
    pricePerNight: definition.pricePerNight,
    cleaningFee: definition.cleaningFee,
    serviceFeePercent: APP_CONFIG.serviceFeePercent,
    currency: APP_CONFIG.currency,
    ratingAverage: definition.ratingAverage,
    ratingCount: definition.ratingCount,
    reviewBreakdown: buildReviewBreakdown(
      definition.ratingAverage,
      definition.id,
    ),
    images: gallery,
    coordinates: { ...definition.coordinates },
    address: {
      street: definition.street,
      city: definition.city,
      state: definition.state,
      country: definition.country ?? "United States",
      zipCode: definition.zipCode,
      neighborhood: definition.neighborhood,
    },
    capacity: { ...definition.capacity },
    amenities: [...definition.amenities],
    blockedRanges,
    minNights: definition.minNights,
    isInstantBook: definition.isInstantBook,
    isRareFind: definition.isRareFind,
    host: buildHostProfile(hostDefinition),
    createdAt,
    updatedAt,
  };
}

/**
 * Materialises the full repository. Pass a fixed `referenceDate` for fully
 * reproducible snapshots (used by the data-integrity check).
 */
export function generateSeedListings(
  referenceDate: Date = new Date(),
): PropertyListing[] {
  return SEED_LISTING_DEFINITIONS.map((definition, index) =>
    buildListingFromDefinition(definition, index, referenceDate),
  );
}

/** The repository consumed by the application at runtime. */
export const INITIAL_LISTINGS: PropertyListing[] = generateSeedListings();

/* -------------------------------------------------------------------------- */
/* 5. Lookups and integrity checks                                            */
/* -------------------------------------------------------------------------- */

export const SEED_LISTING_COUNT: number = INITIAL_LISTINGS.length;

const LISTINGS_BY_ID: ReadonlyMap<string, PropertyListing> = new Map(
  INITIAL_LISTINGS.map((listing) => [listing.id, listing]),
);

const LISTINGS_BY_SLUG: ReadonlyMap<string, PropertyListing> = new Map(
  INITIAL_LISTINGS.map((listing) => [listing.slug, listing]),
);

export function getSeedListingById(id: string): PropertyListing | null {
  return LISTINGS_BY_ID.get(id) ?? null;
}

export function getSeedListingBySlug(slug: string): PropertyListing | null {
  return LISTINGS_BY_SLUG.get(slug) ?? null;
}

/** Distinct `"City, ST"` labels available for search suggestions. */
export const SEED_CITIES: readonly string[] = Array.from(
  new Set(
    INITIAL_LISTINGS.map(
      (listing) => `${listing.address.city}, ${listing.address.state}`,
    ),
  ),
).sort((a, b) => a.localeCompare(b));

/**
 * Verifies repository invariants and returns a list of human-readable issues.
 * An empty array means the repository is safe to render.
 */
export function validateSeedRepository(
  listings: readonly PropertyListing[] = INITIAL_LISTINGS,
): string[] {
  const issues: string[] = [];
  const seenIds = new Set<string>();
  const seenSlugs = new Set<string>();

  if (listings.length < 60) {
    issues.push(
      `expected at least 60 listings, received ${listings.length}`,
    );
  }

  for (const listing of listings) {
    const label = listing.id || "<missing id>";

    if (!isValidListing(listing)) {
      issues.push(`${label}: failed structural validation`);
      continue;
    }

    if (seenIds.has(listing.id)) {
      issues.push(`${label}: duplicate listing id`);
    }
    seenIds.add(listing.id);

    if (seenSlugs.has(listing.slug)) {
      issues.push(`${label}: duplicate slug "${listing.slug}"`);
    }
    seenSlugs.add(listing.slug);

    if (listing.images.length < 3) {
      issues.push(`${label}: gallery must contain at least 3 images`);
    }
    if (new Set(listing.images).size !== listing.images.length) {
      issues.push(`${label}: gallery contains duplicate images`);
    }

    if (listing.pricePerNight < VALIDATION_LIMITS.MIN_PRICE) {
      issues.push(`${label}: nightly price below the minimum`);
    }
    if (listing.amenities.length === 0) {
      issues.push(`${label}: at least one amenity is required`);
    }

    const blockedKeys = new Set<string>();
    for (const range of listing.blockedRanges) {
      const isOrderedIsoRange =
        isIsoDateString(range.startDate) &&
        isIsoDateString(range.endDate) &&
        range.startDate < range.endDate;

      if (!isOrderedIsoRange) {
        issues.push(
          `${label}: invalid blocked range ${range.startDate} → ${range.endDate}`,
        );
        continue;
      }
      const key = `${range.startDate}/${range.endDate}`;
      if (blockedKeys.has(key)) {
        issues.push(`${label}: duplicate blocked range ${key}`);
      }
      blockedKeys.add(key);
    }

    if (!HOSTS_BY_ID.has(listing.host.id)) {
      issues.push(`${label}: host "${listing.host.id}" is not in the roster`);
    }
  }

  return issues;
}

/** Throws when the repository violates any invariant. */
export function assertSeedRepositoryIntegrity(): void {
  const issues = validateSeedRepository();
  if (issues.length > 0) {
    throw new Error(
      `[seed-data] repository integrity check failed:\n- ${issues.join("\n- ")}`,
    );
  }
}
